name: Verify Docs Quality
on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/verify_docs-quality.yml'
      - '**.md'

jobs:
  check-all-files:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      # Vale does not support file excludes, so we use the script to generate a list of files instead
      # The action also does not allow args or a local config file to be passed in, so the files array
      # also contains an "--config=.github/vale/config.ini" option
      - name: generate vale args
        id: generate
        run: echo "args=$(node scripts/check-docs-quality.js --ci-args)" >> $GITHUB_OUTPUT

      - name: documentation quality check
        uses: errata-ai/vale-action@c4213d4de3d5f718b8497bd86161531c78992084 # v2.0.1
        with:
          # This also contains --config=.github/vale/config.ini ... :/
          files: '${{ steps.generate.outputs.args }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
