name: E2E Techdocs
on:
  pull_request:
    paths:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-techdocs.yml'
      - 'packages/techdocs-cli/**'
      - 'packages/techdocs-cli-embedded-app/**'
      - 'plugins/techdocs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    name: Techdocs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: '3.9'

      - name: install dependencies
        run: yarn install --immutable

      - name: generate types
        run: yarn tsc

      - name: build techdocs-cli
        working-directory: packages/techdocs-cli
        run: yarn build

      - name: Install mkdocs & techdocs-core
        run: python -m pip install mkdocs-techdocs-core==1.1.7 mkdocs==1.4.0

      - name: techdocs-cli e2e test
        working-directory: packages/techdocs-cli
        run: yarn test:e2e:ci
        env:
          BACKSTAGE_TEST_DISABLE_DOCKER: 1
